[package]
name = "kronos"
version = "0.2.0"
edition = "2024"
license = "MIT"
authors = ["Rodolfo Granata <warlock.cc@gmail.com>"]
description = "A tool to calculate complex time expressions"
repository = "https://github.com/rodolf0/tox/tree/master/kronos"
readme = "README.md"
keywords = ["time", "date", "calendar", "chrono", "sequence"]
categories = ["date-and-time"]

[dependencies]
# NOTE macros only used for tests but can't easily 
# toggle them off. So we keep thm for release builds too.
time = { version = "0.3", features = ["macros"] }
