[package]
name = "fluxcap"
version = "0.2.0"
edition = "2024"
authors = ["Rodolfo Granata <warlock.cc@gmail.com>"]
description = "time expression parsing inspired on duckling"
license = "MIT"
repository = "https://github.com/rodolf0/tox"

[dependencies]
earlgrey = { workspace = true }
kronos = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true, features = ["macros", "local-offset", "parsing", "formatting"] }
