[package]
name = "fluxcap"
version = "0.1.4"
edition = "2024"
authors = ["Rodolfo Granata <warlock.cc@gmail.com>"]
description = "time expression parsing inspired on duckling"
license = "MIT"
repository = "https://github.com/rodolf0/tox"

[dependencies]
earlgrey = { version = "0.4", path = "../earlgrey" }
kronos = { version = "0.2", path = "../kronos" }
time = { version = "0.3", features = ["macros"] }
