[package]
name = "fluxcap"
version = "0.1.5"
edition = "2024"
authors = ["Rodolfo Granata <warlock.cc@gmail.com>"]
description = "time expression parsing inspired on duckling"
license = "MIT"
repository = "https://github.com/rodolf0/tox"

[dependencies]
earlgrey = { version = "0.4", path = "../earlgrey" }
kronos = { version = "0.2", path = "../kronos" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
time = { version = "0.3", features = ["macros", "local-offset", "parsing", "formatting"] }
