[package]
name = "tomathin"
version = "0.1.0"
edition = "2021"

[dependencies]
earlgrey = { version = "0.4", path = "../earlgrey" }
rustyline = { version = "14.0.0" }
rand_distr = "0.4.3"
rand = "0.8.5"
