// A TimeSeq is a generator of TimeSpans
//   a |----|----|----|----|----|----|----|----|
//
// A TimeSpan is a right-open time interval. [----)
// The grain determines up to what granularity start/end timepoints are valid.
//
// To make a sequence generate TimeSpan items the generator
// needs to be anchored at a point in time t0.
//
//     s0   s1   s2   s3   s4 ....
//   a |----|----|----|----|----|----|----|----|
//        ^
//        | t0
//
// The 1st TimeSpan item in the sequence (generated by seq) will contain t0 unless
// its impossible because of a non-complete sequence.
// - Iterating into the future the the start of the first element will be greater than t0.
// - Iterating into the past the the end of the first element will be less or eq than t0.
//
// When iterating into the past. The same applies t0 will be contained by the
// first emitted TimeSpan (unless impossible because of a non-complete sequence).
//
// Given right-open intervals, if t0 aligns with the end of a sequence (hence the
// start of the next) the 1st element will seem like an item into the future.
// The user can restrict the 1st item to be in the past by checking end <= t0.
//
// Iterating into the past and future will overlap on their 1st element. The user
// can choose to ignore this overlap by checking if t0 is contained and skip.
// This is what 'future' and 'past' methods do, they filter the 'seq' method properly.
//
//
// # Operations combining sequences
//
// Different overlap types between 2 sequences:
//
//   [------a------)
//            [------b------)
//
//   [----a----)
//                [-----b-----)
//
//   [---------a---------)
//        [-----b-----)
//
// - and - Intersection: eg June and summer, 3pm on Saturdays
// - or - Union: eg Mondays and Tuesdays, 1st and 3rd day of the month
// - diff - Except: Days in June except Mondays, Tuesdays except March
// - Within: 3rd monday of May, Last hour of the day
// - apply - first do this ... graph traversal ?
//
//
// An anchored TimeSeq implements the Iterator trait and you
// can transform items as needed with iterator methods.

use std::collections::VecDeque;
use time::{Duration, UtcDateTime as DateTime};

#[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Clone, Copy)]
pub enum Grain {
    Second,
    Minute,
    Hour,
    Day,
    Month,
    Year,
}

#[derive(Debug, PartialEq, Clone)]
pub struct TimeSpan {
    pub(crate) start: DateTime,
    pub(crate) end: DateTime,
    pub(crate) grain: Grain,
}

impl TimeSpan {
    pub fn intersect(&self, other: &TimeSpan) -> Option<TimeSpan> {
        use std::cmp;
        if self.start < other.end && self.end > other.start {
            return Some(TimeSpan {
                start: cmp::max(self.start, other.start),
                end: cmp::min(self.end, other.end),
                grain: cmp::min(self.grain, other.grain),
            });
        }
        None
    }

    pub fn contains(&self, t: &DateTime) -> bool {
        self.start <= *t && *t < self.end
    }

    pub fn shift(self, grain: Grain, n: i32) -> Self {
        TimeSpan {
            start: shift(self.start, grain, n),
            end: shift(self.end, grain, n),
            grain: self.grain,
        }
    }

    pub fn year(y: i32) -> Self {
        let start = DateTime::new(
            time::Date::from_calendar_date(y, time::Month::January, 1).unwrap(),
            time::Time::MIDNIGHT,
        );
        TimeSpan {
            start,
            end: start.replace_year(y + 1).unwrap(),
            grain: Grain::Year,
        }
    }
}

// Shift a DateTime by a given number of grain-counts.
// Day of the month may be clamped in case of month change or leap year.
fn shift(t0: DateTime, grain: Grain, n: i32) -> DateTime {
    if n == 0 {
        return t0;
    }
    match grain {
        Grain::Second => t0 + Duration::seconds(n as i64),
        Grain::Minute => t0 + Duration::minutes(n as i64),
        Grain::Hour => t0 + Duration::hours(n as i64),
        Grain::Day => t0 + Duration::days(n as i64),
        Grain::Month => {
            let (year, month, day) = t0.to_calendar_date();
            // Work in month space
            let zero_indexed_month = month as i32 - 1;
            let total_months = year * 12 + zero_indexed_month + n;
            // Convert back to year and month
            let n_year = total_months.div_euclid(12);
            let n_zero_month = total_months.rem_euclid(12);
            let n_month = time::Month::try_from(n_zero_month as u8 + 1).expect("BUG: bad month");
            // Check if the day needs to be clamped because of month change
            let n_day = day.min(n_month.length(n_year));
            t0.replace_date(
                time::Date::from_calendar_date(n_year, n_month, n_day).expect("BUG: bad date"),
            )
        }
        Grain::Year => {
            // Eg: for Feb 29th max day needs adjustment.
            let max_month_days = t0.month().length(t0.year() + n);
            t0.replace_day(t0.day().min(max_month_days))
                .and_then(|t| t.replace_year(t0.year() + n))
                .expect(&format!(
                    "BUG: bad year shift t0={}, n={}, g={:?}",
                    t0, n, grain
                ))
        }
    }
}

fn truncate(t0: DateTime, grain: Grain) -> DateTime {
    use Grain::*;
    match grain {
        Second => Ok(t0),
        Minute => t0.replace_second(0),
        Hour => t0.replace_minute(0).and_then(|t| t.replace_second(0)),
        Day => Ok(t0.replace_time(time::Time::MIDNIGHT)),
        Month => t0.replace_time(time::Time::MIDNIGHT).replace_day(1),
        Year => t0
            .replace_time(time::Time::MIDNIGHT)
            .replace_day(1)
            .and_then(|t| t.replace_month(time::Month::January)),
    }
    // The rounding in truncate should never be invalid.
    .expect("BUG: truncation failed")
}

fn truncate_week(t0: DateTime) -> DateTime {
    let t0 = t0.replace_time(time::Time::MIDNIGHT);
    let week_days_offset = t0.weekday().number_days_from_sunday();
    t0 - Duration::days(week_days_offset as i64)
}

fn truncate_weekend(t0: DateTime) -> DateTime {
    // Make sure find_weekend was called before truncate_weekend
    assert!(
        t0.weekday() != time::Weekday::Saturday || t0.weekday() != time::Weekday::Sunday,
        "truncate_weekend needs to be called on a weekend "
    );
    let t0 = t0.replace_time(time::Time::MIDNIGHT);
    match t0.weekday() {
        time::Weekday::Saturday => t0,
        time::Weekday::Sunday => t0 - Duration::days(1),
        _ => unreachable!(),
    }
}

// Generate sequences of time ranges. Each element will have window_span template.
fn grain_iterator(
    t0: DateTime,
    window_span: (Grain, u32),
    step_by: (Grain, i32),
) -> impl Iterator<Item = TimeSpan> {
    // Mask t0's resolution beyond the grain of the span
    let t0 = truncate(t0, window_span.0);
    (0..).map(move |i| {
        let start = shift(t0, step_by.0, i * step_by.1);
        let end = shift(start, window_span.0, window_span.1 as i32);
        TimeSpan {
            start,
            end,
            grain: window_span.0,
        }
    })
}

fn grains_in_parent(grain: Grain) -> u16 {
    match grain {
        Grain::Second => 60,
        Grain::Minute => 60,
        Grain::Hour => 24,
        Grain::Day => panic!("Day is not a valid grain for grains_in_parent"),
        Grain::Month => 12,
        Grain::Year => panic!("Year is not a valid grain for grains_in_parent"),
    }
}

fn find_grain(mut t0: DateTime, grain: Grain, n: u16) -> DateTime {
    while match grain {
        Grain::Second => t0.second() as u16,
        Grain::Minute => t0.minute() as u16,
        Grain::Hour => t0.hour() as u16,
        Grain::Day => t0.day() as u16,
        Grain::Month => t0.month() as u16,
        Grain::Year => panic!("Year is not a valid grain for find_grain"),
    } != n
    {
        t0 = shift(t0, grain, 1);
    }
    t0
}

fn find_weekend(mut t0: DateTime) -> DateTime {
    while t0.weekday() != time::Weekday::Saturday && t0.weekday() != time::Weekday::Sunday {
        t0 = shift(t0, Grain::Day, 1);
    }
    t0
}

fn find_weekday(mut t0: DateTime, weekday: u8) -> DateTime {
    while t0.weekday().number_days_from_sunday() != weekday {
        t0 = shift(t0, Grain::Day, 1);
    }
    t0
}

#[derive(Clone, Debug)]
pub(crate) enum SeqSpecInternal {
    Grain {
        window_span: (Grain, u32),
        step_by: (Grain, i32),
    },
    SpecificGrain {
        grain: Grain,
        n: u16,
    },
    Monthdays(u8),
    Weekdays(u8), // Sunday=0
    Weekends,
    Weeks,
    Within {
        nth: isize,
        window: Box<SeqSpecInternal>,
        frame: Box<SeqSpecInternal>,
    },
    // merge multiple TimeSpans into one
    Merge(Box<SeqSpecInternal>, u8),
    // Union emits the elements of both streams in order
    Union(Box<SeqSpecInternal>, Box<SeqSpecInternal>),
    Intersection(Box<SeqSpecInternal>, Box<SeqSpecInternal>),
    Except(Box<SeqSpecInternal>, Box<SeqSpecInternal>),
    Shift(Box<SeqSpecInternal>, Grain, i32),
    // Example: Sep 21st to Dec 21st - inclusive (Spring in South)
    // Example: Mon through Friday
    Interval {
        from: Box<SeqSpecInternal>,
        to: Box<SeqSpecInternal>,
        inclusive: bool,
    },
}

#[derive(Clone, Debug)]
pub struct TimeSeqSpec(pub(crate) SeqSpecInternal);

impl TimeSeqSpec {
    pub fn seconds(n: Option<u16>) -> TimeSeqSpec {
        TimeSeqSpec(match n {
            Some(n) => SeqSpecInternal::SpecificGrain {
                grain: Grain::Second,
                n,
            },
            None => SeqSpecInternal::Grain {
                window_span: (Grain::Second, 1),
                step_by: (Grain::Second, 1),
            },
        })
    }

    pub fn minutes(n: Option<u16>) -> TimeSeqSpec {
        TimeSeqSpec(match n {
            Some(n) => SeqSpecInternal::SpecificGrain {
                grain: Grain::Minute,
                n,
            },
            None => SeqSpecInternal::Grain {
                window_span: (Grain::Minute, 1),
                step_by: (Grain::Minute, 1),
            },
        })
    }

    pub fn hours(n: Option<u16>) -> TimeSeqSpec {
        TimeSeqSpec(match n {
            Some(n) => SeqSpecInternal::SpecificGrain {
                grain: Grain::Hour,
                n,
            },
            None => SeqSpecInternal::Grain {
                window_span: (Grain::Hour, 1),
                step_by: (Grain::Hour, 1),
            },
        })
    }

    pub fn days() -> TimeSeqSpec {
        TimeSeqSpec(SeqSpecInternal::Grain {
            window_span: (Grain::Day, 1),
            step_by: (Grain::Day, 1),
        })
    }

    pub fn months(n: Option<u16>) -> TimeSeqSpec {
        TimeSeqSpec(match n {
            Some(n) => SeqSpecInternal::SpecificGrain {
                grain: Grain::Month,
                n,
            },
            None => SeqSpecInternal::Grain {
                window_span: (Grain::Month, 1),
                step_by: (Grain::Month, 1),
            },
        })
    }

    pub fn weeks() -> TimeSeqSpec {
        TimeSeqSpec(SeqSpecInternal::Weeks)
    }

    pub fn years() -> TimeSeqSpec {
        TimeSeqSpec(SeqSpecInternal::Grain {
            window_span: (Grain::Year, 1),
            step_by: (Grain::Year, 1),
        })
    }

    pub fn weekends() -> TimeSeqSpec {
        TimeSeqSpec(SeqSpecInternal::Weekends)
    }

    pub fn weekday(day: u8) -> TimeSeqSpec {
        TimeSeqSpec(SeqSpecInternal::Weekdays(day))
    }

    pub fn monthday(day: u8) -> TimeSeqSpec {
        TimeSeqSpec(SeqSpecInternal::Monthdays(day))
    }

    pub fn union(self, other: Self) -> Result<Self, String> {
        if self.0.grain() != other.0.grain() {
            Err("Union grains must be the same".to_string())
        } else {
            Ok(TimeSeqSpec(SeqSpecInternal::Union(Box::new(self.0), Box::new(other.0))))
        }
    }

    pub fn within(self, frame: Self, nth: isize) -> Result<Self, String> {
        if self.0.grain() >= frame.0.grain() {
            Err("Within needs win grain < frame grain".to_string())
        } else {
            Ok(TimeSeqSpec(SeqSpecInternal::Within {
                nth,
                window: Box::new(self.0),
                frame: Box::new(frame.0),
            }))
        }
    }

    pub fn merge(self, n: u8) -> Self {
        TimeSeqSpec(SeqSpecInternal::Merge(Box::new(self.0), n))
    }

    pub fn intersection(self, other: Self) -> Self {
        TimeSeqSpec(SeqSpecInternal::Intersection(Box::new(self.0), Box::new(other.0)))
    }

    pub fn except(self, other: Self) -> Self {
        TimeSeqSpec(SeqSpecInternal::Except(Box::new(self.0), Box::new(other.0)))
    }

    pub fn shift(self, grain: Grain, n: i32) -> Self {
        TimeSeqSpec(SeqSpecInternal::Shift(Box::new(self.0), grain, n))
    }

    pub fn to(self, other: Self, inclusive: bool) -> Self {
        TimeSeqSpec(SeqSpecInternal::Interval {
            from: Box::new(self.0),
            to: Box::new(other.0),
            inclusive,
        })
    }
}

impl SeqSpecInternal {
    fn grain(&self) -> Grain {
        use std::cmp;
        match self {
            SeqSpecInternal::Grain {
                window_span: (grain, _),
                step_by: _,
            } => *grain,
            SeqSpecInternal::SpecificGrain { grain, n: _ } => *grain,
            SeqSpecInternal::Monthdays(_) => Grain::Day,
            SeqSpecInternal::Weekdays(_) => Grain::Day,
            SeqSpecInternal::Weekends => Grain::Day,
            SeqSpecInternal::Weeks => Grain::Day,
            SeqSpecInternal::Within {
                nth: _,
                window,
                frame: _,
            } => window.grain(),
            SeqSpecInternal::Merge(s, _) => s.grain(),
            // Constructor asserts that s1 and s2 have the same grain
            SeqSpecInternal::Union(s1, _) => s1.grain(),
            SeqSpecInternal::Intersection(s1, s2) => cmp::min(s1.grain(), s2.grain()),
            SeqSpecInternal::Except(s1, _) => s1.grain(),
            SeqSpecInternal::Shift(s1, _, _) => s1.grain(),
            SeqSpecInternal::Interval {
                from,
                to,
                inclusive: _,
            } => std::cmp::min(from.grain(), to.grain()),
        }
    }
}

// Guard against impossible sequences, eg: 32nd day of the month
const INFINITE_FUSE: usize = 1000;

#[derive(PartialEq, Clone, Copy)]
pub(crate) enum TimeDir {
    Future,
    Past,
}

pub type TimeSequence = Box<dyn Iterator<Item = TimeSpan>>;

impl SeqSpecInternal {
    pub(crate) fn seq(self, t0: DateTime, direction: TimeDir) -> TimeSequence {
        match self {
            SeqSpecInternal::Grain {
                window_span,
                step_by: (sb_grain, sb_n),
            } => {
                let step = match direction {
                    TimeDir::Future => sb_n,
                    TimeDir::Past => -sb_n,
                };
                Box::new(grain_iterator(t0, window_span, (sb_grain, step)))
            }
            SeqSpecInternal::Weeks => {
                let t0 = truncate_week(t0);
                let step_by = match direction {
                    TimeDir::Future => (Grain::Day, 7),
                    TimeDir::Past => (Grain::Day, -7),
                };
                Box::new(grain_iterator(t0, (Grain::Day, 7), step_by))
            }
            SeqSpecInternal::Weekdays(n) => {
                let t0 = find_weekday(t0, n);
                let step_by = match direction {
                    TimeDir::Future => (Grain::Day, 7),
                    TimeDir::Past => (Grain::Day, -7),
                };
                Box::new(grain_iterator(t0, (Grain::Day, 1), step_by))
            }
            SeqSpecInternal::Monthdays(n) => {
                let mut t0_end = t0;
                Box::new(std::iter::from_fn(move || {
                    while t0_end.day() != n {
                        t0_end += match direction {
                            TimeDir::Future => Duration::days(1),
                            TimeDir::Past => Duration::days(-1),
                        }
                    }
                    t0_end += match direction {
                        TimeDir::Future => Duration::days(1),
                        TimeDir::Past => Duration::days(-1),
                    };
                    Some(TimeSpan {
                        start: t0_end + Duration::days(-1),
                        end: t0_end,
                        grain: Grain::Day,
                    })
                }))
            }
            SeqSpecInternal::Weekends => {
                let t0 = find_weekend(t0);
                let t0 = truncate_weekend(t0);
                let step_by = match direction {
                    TimeDir::Future => (Grain::Day, 7),
                    TimeDir::Past => (Grain::Day, -7),
                };
                Box::new(grain_iterator(t0, (Grain::Day, 2), step_by))
            }
            SeqSpecInternal::SpecificGrain { grain, n } => {
                let t0 = find_grain(t0, grain, n);
                let step_by = match direction {
                    TimeDir::Future => (grain, grains_in_parent(grain) as i32),
                    TimeDir::Past => (grain, -(grains_in_parent(grain) as i32)),
                };
                Box::new(grain_iterator(t0, (grain, 1), step_by))
            }
            SeqSpecInternal::Within { nth, window, frame } => {
                Box::new(
                    frame
                        .seq(t0, direction)
                        .take(INFINITE_FUSE)
                        .filter_map(move |f| {
                            let window = window.clone();
                            if nth > 0 {
                                window
                                    .seq(f.start, TimeDir::Future)
                                    // Each window has to start within frame's boundary
                                    .take_while(|w| w.start < f.end)
                                    .nth((nth - 1) as usize)
                            } else {
                                let nth = -nth as usize;
                                let mut deque = VecDeque::with_capacity(nth);
                                // Consume the whole iterator and keep the tail.
                                for w in window
                                    .seq(f.start, TimeDir::Future)
                                    // Each window has to start within frame's boundary
                                    .take_while(|w| w.start < f.end)
                                {
                                    deque.truncate(nth - 1);
                                    deque.push_front(w);
                                }
                                // Not poping the back because it may be shorter than nth.
                                deque.remove(nth - 1)
                            }
                        }),
                )
            }
            SeqSpecInternal::Merge(s, n) => {
                let mut _s = match direction {
                    TimeDir::Future => s.seq(t0, direction).skip(0),
                    TimeDir::Past => s.seq(t0, direction).skip(1),
                };
                Box::new(std::iter::from_fn(move || {
                    let _s2 = _s.by_ref();
                    let spans: Vec<_> = _s2.take(n as usize).collect();
                    match direction {
                        TimeDir::Future => Some(TimeSpan {
                            start: spans.first().unwrap().start,
                            end: spans.last().unwrap().end,
                            grain: spans.first().unwrap().grain,
                        }),
                        TimeDir::Past => Some(TimeSpan {
                            start: spans.last().unwrap().start,
                            end: spans.first().unwrap().end,
                            grain: spans.first().unwrap().grain,
                        }),
                    }
                }))
            }
            SeqSpecInternal::Union(s1, s2) => {
                let mut s1 = s1.seq(t0, direction).peekable();
                let mut s2 = s2.seq(t0, direction).peekable();
                let starts_first = match direction {
                    TimeDir::Future => |n1: &TimeSpan, n2: &TimeSpan| n1.start <= n2.start,
                    TimeDir::Past => |n1: &TimeSpan, n2: &TimeSpan| n1.start > n2.start,
                };
                Box::new(std::iter::from_fn(move || {
                    // emit the span that starts first
                    match (s1.peek(), s2.peek()) {
                        (Some(n1), Some(n2)) => {
                            if starts_first(n1, n2) {
                                s1.next()
                            } else {
                                s2.next()
                            }
                        }
                        (Some(_), None) => s1.next(),
                        (None, Some(_)) => s2.next(),
                        (None, None) => None,
                    }
                }))
            }
            SeqSpecInternal::Intersection(s1, s2) => {
                let mut s1 = s1.seq(t0, direction).peekable();
                let mut s2 = s2.seq(t0, direction).peekable();
                let ends_first = match direction {
                    TimeDir::Future => |n1: &TimeSpan, n2: &TimeSpan| n1.end <= n2.end,
                    TimeDir::Past => |n1: &TimeSpan, n2: &TimeSpan| n1.start >= n2.start,
                };
                Box::new(std::iter::from_fn(move || {
                    for _ in 0..INFINITE_FUSE {
                        match (s1.peek(), s2.peek()) {
                            (Some(n1), Some(n2)) => {
                                let overlap = n1.intersect(&n2);
                                // advance the stream that is lagging
                                if ends_first(n1, n2) {
                                    s1.next()
                                } else {
                                    s2.next()
                                };
                                if overlap.is_some() {
                                    return overlap;
                                }
                            }
                            // If either stream ended there's no more intersections
                            _ => return None,
                        }
                    }
                    None // panic!("Intersect INFINITE_FUSE blown");
                }))
            }
            SeqSpecInternal::Except(s, except) => {
                let s = s.seq(t0, direction);
                let mut except = except.seq(t0, direction);
                let mut ex = except.next();
                let except_lagging_seq = match direction {
                    TimeDir::Future => |s1: &TimeSpan, ex: &TimeSpan| ex.end < s1.start,
                    TimeDir::Past => |s1: &TimeSpan, ex: &TimeSpan| ex.start >= s1.end,
                };
                Box::new(s.filter(move |span| {
                    // Catchup the except seq to the stream to know if they intersect
                    while ex.as_ref().is_some_and(|ex| except_lagging_seq(span, &ex)) {
                        ex = except.next();
                    }
                    match &ex {
                        Some(ex) => span.intersect(&ex).is_none(),
                        None => true,
                    }
                }))
            }
            SeqSpecInternal::Shift(s, grain, n) => {
                Box::new(s.seq(t0, direction).map(move |s| s.shift(grain, n)))
            }
            SeqSpecInternal::Interval {
                from,
                to,
                inclusive,
            } => {
                // The first emitted item (future or past) should contain t0.
                // Item needs to be strictly less than (contained by) 'to''s item.
                // So adjust t0 to 1) be inside the interval, 2) truncate it to start.
                let t0 = to
                    .clone()
                    .seq(t0, direction)
                    .next()
                    .map(|s| if inclusive { s.end } else { s.start });
                // This is the 'truncate' to interval boundary/start.
                // Find interval start back from the just-found interval end.
                let t0 = t0
                    .and_then(|t0| {
                        // find interval starting point
                        from.clone()
                            .seq(t0, TimeDir::Past)
                            .skip_while(|t| t.end > t0) // 1st seq Past item contains t0
                            .next()
                    })
                    .map(|s| s.start);
                // If we couldn't find a reasonable t0 then there's no viable TimeSeq
                let t0 = match t0 {
                    Some(t0) => t0,
                    None => return Box::new(std::iter::empty()),
                };
                // Grain will be the smallest resolution of either grain
                let grain = std::cmp::min(from.grain(), to.grain());
                Box::new(
                    from.seq(t0, direction)
                        .take(INFINITE_FUSE)
                        .filter_map(move |f| {
                            match to.clone().seq(f.start, TimeDir::Future).next() {
                                Some(t) => Some(TimeSpan {
                                    start: f.start,
                                    end: if inclusive { t.end } else { t.start },
                                    grain,
                                }),
                                None => None,
                            }
                        }),
                )
            }
        }
    }
}

impl TimeSeqSpec {
    pub fn future(self, t0: DateTime) -> TimeSequence {
        Box::new(
            self.0.seq(t0, TimeDir::Future)
                .skip_while(move |t| t.end <= t0),
        )
    }

    pub fn past(self, t0: DateTime) -> TimeSequence {
        Box::new(self.0.seq(t0, TimeDir::Past).skip_while(move |t| t.end > t0))
    }
}
