[package]
name = "numerica"
version = "0.1.0"
edition = "2024"

[dependencies]
earlgrey = { version = "0.4", path = "../earlgrey" }
rand_distr = "0.5"
rand = "0.9"
libm = { version = "0.2", optional = true }

[features]
# By default don't include libm just link libc math. For WASM use libm
default = []
use-libm = ["libm"]
