[package]
name = "numerica"
version = "0.1.1"
edition = "2024"

[dependencies]
earlgrey = { workspace = true }
rand_distr = { workspace = true }
rand = { workspace = true }
libm = { workspace = true, optional = true }
fluxcap = { workspace = true }


[features]
# By default don't include libm just link libc math. For WASM use libm
default = []
use-libm = ["libm"]
