[package]
name = "shunting"
version = "0.1.3"
edition = "2024"
license = "MIT"
authors = ["Rodolfo Granata <warlock.cc@gmail.com>"]
description = "A library for evaluating math expressions"
repository = "https://github.com/rodolf0/tox/tree/master/shunting"
readme = "README.md"
keywords = ["shunting", "math", "parser", "expression", "eval"]
categories = ["parsing", "algorithms"]

[dependencies]
lexers = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
libm = { workspace = true }


